### ISSUE TITLE
cant load preferences

### ISSUE THREAD

**Issue by avonar** [easonwong-de/Adaptive-Tab-Bar-Color#45]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/668939/218417700-857fd285-4994-40f0-abef-21fb46c068e0.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/668939/218417758-586b0cc6-5b19-41c5-959f-3583a7fc5ec4.png">

There are no posiiblity to load prefernces after any changes in settings and restarted browser.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/668939/218418103-77a9d64f-7e47-4609-b2df-1762cbbfe3b2.png">

**Comment by YS-Wong** [comment]
This was actually a problem before, and I thought this is solved in the latest version.

For temporary fix, please remove the add-on and install it again. I’m terribly sorry for the inconvenience.

**Comment by avonar** [comment]
yes, so this is working only if i remove the extentions, install again, change all settings, and dont want change any color more. :)

Hope you will fix it, because this extention is the best for me,  thank you !

**Comment by YS-Wong** [comment]
Yes, I’ll look into it.

**Comment by easonwong-de** [comment]
@avonar The latest version v1.7.3 is published, which is meant to solve the eternal loading bug. Feel free to have a try.

**Comment by avonar** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/668939/220044068-068cf84b-5241-4e60-8242-3c5b3197af1b.png">
1)i had removed the extension and reloaded the browser
2)install an extension from the store
the problem still exists, but now it tells me that this is corrupted

**Comment by easonwong-de** [comment]
I’m sorry I closed the issue, because I couldn’t replicate the bug and I assumed this is solved. Could you make a screenshot in the backend console of the add-on? You can find it here: `about:debugging#/runtime/this-firefox`

<img width="678" alt="Screenshot 2023-02-20 at 08 54 54" src="https://user-images.githubusercontent.com/16183548/220045834-e8934255-9e66-48fb-87c9-ccee7002fde8.png">

**Comment by easonwong-de** [comment]
If no error message is presented, could you type in `browser.storage.local.get()`, and unfold the answer? It will look something like this:

<img width="744" alt="Screenshot 2023-02-20 at 08 58 14" src="https://user-images.githubusercontent.com/16183548/220046314-40f6ebaf-140c-4957-8c3c-d318f57668bc.png">

**Comment by avonar** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/668939/220046775-fa9af14a-b68b-40e0-a829-f6ba5293b90c.png">

**Comment by easonwong-de** [comment]
@avonar Thanks for the reply. I’m working on it.

**Comment by easonwong-de** [comment]
There’s a `undefined: undefined` in `reservedColor_cs`. I think that causes the problem.

**Comment by easonwong-de** [comment]
<img width="685" alt="Screenshot 2023-02-20 at 09 05 52" src="https://user-images.githubusercontent.com/16183548/220047799-1e54ddaa-79ff-4ac1-bc8a-00ef1f74e488.png">

Gotcha!

**Comment by easonwong-de** [comment]
A quick temporary fix will be:

```
browser.storage.local.get(pref => {
	let temp = pref.reservedColor_cs;
	delete temp[undefined]
  browser.storage.local.set({reservedColor_cs: temp})
});
```

**Comment by avonar** [comment]
will it remove colors that are already set?
because now, it can't load preferences, yes, so i cant set new sites, but still is working on different tabs.

**Comment by easonwong-de** [comment]
No. This script will only remove the corrupted part.

**Comment by easonwong-de** [comment]
Until the next version, please avoid setting the “set color for specific domains” part.

**Comment by easonwong-de** [comment]
As it turns out, literally one single number broke everything. Now v1.7.4 is out, which is also capable of fixing broken data.
